#!/bin/bash

### Atari 2600
envs=(
#     "AssaultNoFrameskip-v4"
#     "AtlantisNoFrameskip-v4"
#     "BankHeistNoFrameskip-v4"
#     "BoxingNoFrameskip-v4"
#     "BreakoutNoFrameskip-v4"
#     "CrazyClimberNoFrameskip-v4"
     "DefenderNoFrameskip-v4"
#     "DemonAttackNoFrameskip-v4"
#     "DoubleDunkNoFrameskip-v4"
#     "EnduroNoFrameskip-v4"
#     "FishingDerbyNoFrameskip-v4"
#     "FreewayNoFrameskip-v4"
#     "GopherNoFrameskip-v4"
#     "JamesbondNoFrameskip-v4"
#     "KangarooNoFrameskip-v4"
#     "KrullNoFrameskip-v4"
#     "KungFuMasterNoFrameskip-v4"
#     "NameThisGameNoFrameskip-v4"
     "PhoenixNoFrameskip-v4"
#     "PongNoFrameskip-v4"
#     "QbertNoFrameskip-v4"
#     "RoadRunnerNoFrameskip-v4"
#     "StarGunnerNoFrameskip-v4"
#     "TutankhamNoFrameskip-v4"
#     "UpNDownNoFrameskip-v4"
#     "VideoPinballNoFrameskip-v4"

#    "ALE/Blackjack-v5"
#    "ALE/VideoChess-v5"
#    "ALE/VideoCheckers-v5"
#    "ALE/Turmoil-v5"
#    "ALE/Trondead-v5"
#    "ALE/TicTacToe3D-v5"
#    "ALE/Tetris-v5"
#    "ALE/Surround-v5"
#    "ALE/Superman-v5"
#    "ALE/SpaceWar-v5"
#    "ALE/Othello-v5"
#    "ALE/MrDo-v5"
#    "ALE/MiniatureGolf-v5"
#    "ALE/LostLuggage-v5"
#    "ALE/LaserGates-v5"
#    "ALE/KingKong-v5"
#    "ALE/KeystoneKapers-v5"
#    "ALE/Kaboom-v5"
#    "ALE/Hangman-v5"
#    "ALE/Galaxian-v5"
#    "ALE/Frogger-v5"
#    "ALE/DonkeyKong-v5"
#    "ALE/Casino-v5"
#    "ALE/BasicMath-v5"
)

# Loop through each environment and run the trainer
for env in "${envs[@]}"; do
    echo "--------------------------------------------------"
    echo "Starting training for: $env"
    echo "--------------------------------------------------"

    python3 ./sb3_agents/trainer.py --emulator ale --env "$env"

    echo "Finished training for: $env"
done