#!/bin/bash

### Atari 2600
envs=(
#     "AssaultNoFrameskip-v4"
#     "AtlantisNoFrameskip-v4"
#     "BankHeistNoFrameskip-v4"
#     "BoxingNoFrameskip-v4"
#     "BreakoutNoFrameskip-v4"
#     "CrazyClimberNoFrameskip-v4"
#     "DefenderNoFrameskip-v4"
#     "DemonAttackNoFrameskip-v4"
#     "DoubleDunkNoFrameskip-v4"
#     "EnduroNoFrameskip-v4"
#     "FishingDerbyNoFrameskip-v4"
#     "FreewayNoFrameskip-v4"
#     "GopherNoFrameskip-v4"
#     "JamesbondNoFrameskip-v4"
#     "KangarooNoFrameskip-v4"
#     "KrullNoFrameskip-v4"
#     "KungFuMasterNoFrameskip-v4"
#     "NameThisGameNoFrameskip-v4"
#     "PhoenixNoFrameskip-v4"
#     "PongNoFrameskip-v4"
#     "QbertNoFrameskip-v4"
#     "RoadRunnerNoFrameskip-v4"
#     "StarGunnerNoFrameskip-v4"
#     "TutankhamNoFrameskip-v4"
#     "UpNDownNoFrameskip-v4"
#     "VideoPinballNoFrameskip-v4"

#    "ALE/Blackjack-v5"
#    "ALE/VideoChess-v5"
#    "ALE/VideoCheckers-v5"
#    "ALE/Turmoil-v5"
#    "ALE/Trondead-v5"
#    "ALE/TicTacToe3D-v5"
#    "ALE/Tetris-v5"
#    "ALE/Surround-v5"
#    "ALE/Superman-v5"
#    "ALE/SpaceWar-v5"
#    "ALE/Othello-v5"
#    "ALE/MrDo-v5"
#    "ALE/MiniatureGolf-v5"
#    "ALE/LostLuggage-v5"
#    "ALE/LaserGates-v5"
#    "ALE/KingKong-v5"
#    "ALE/KeystoneKapers-v5"
#    "ALE/Kaboom-v5"
#    "ALE/Hangman-v5"
#    "ALE/Galaxian-v5"
#    "ALE/Frogger-v5"
#    "ALE/DonkeyKong-v5"
#    "ALE/Casino-v5"
#    "ALE/BasicMath-v5"

     "AdventureNoFrameskip-v4"
     "AirRaidNoFrameskip-v4"
     "AlienNoFrameskip-v4"
     "AmidarNoFrameskip-v4"
     "AsterixNoFrameskip-v4"
     "AsteroidsNoFrameskip-v4"
     "Atlantis2NoFrameskip-v4"
     "BackgammonNoFrameskip-v4"
     "BattleZoneNoFrameskip-v4"
     "BeamRiderNoFrameskip-v4"
     "BerzerkNoFrameskip-v4"
     "BowlingNoFrameskip-v4"
     "CarnivalNoFrameskip-v4"
     "CentipedeNoFrameskip-v4"
     "ChopperCommandNoFrameskip-v4"
     "CrossbowNoFrameskip-v4"
     "DarkchambersNoFrameskip-v4"
     "EarthworldNoFrameskip-v4"
     "ElevatorActionNoFrameskip-v4"
     "EntombedNoFrameskip-v4"
     "EtNoFrameskip-v4"
     "FlagCaptureNoFrameskip-v4"
     "FrostbiteNoFrameskip-v4"
     "GravitarNoFrameskip-v4"
     "HauntedHouseNoFrameskip-v4"
     "HeroNoFrameskip-v4"
     "HumanCannonballNoFrameskip-v4"
     "IceHockeyNoFrameskip-v4"
     "JourneyEscapeNoFrameskip-v4"
     "KlaxNoFrameskip-v4"
     "KoolaidNoFrameskip-v4"
     "MarioBrosNoFrameskip-v4"
     "MontezumaRevengeNoFrameskip-v4"
     "MsPacmanNoFrameskip-v4"
     "PacmanNoFrameskip-v4"
     "PitfallNoFrameskip-v4"
     "Pitfall2NoFrameskip-v4"
     "PooyanNoFrameskip-v4"
     "PrivateEyeNoFrameskip-v4"
     "RiverraidNoFrameskip-v4"
     "RobotankNoFrameskip-v4"
     "SeaquestNoFrameskip-v4"
     "SirLancelotNoFrameskip-v4"
     "SkiingNoFrameskip-v4"
     "SolarisNoFrameskip-v4"
     "SpaceInvadersNoFrameskip-v4"
     "TennisNoFrameskip-v4"
     "TimePilotNoFrameskip-v4"
     "VentureNoFrameskip-v4"
     "VideoCubeNoFrameskip-v4"
     "WizardOfWorNoFrameskip-v4"
     "WordZapperNoFrameskip-v4"
     "YarsRevengeNoFrameskip-v4"
     "ZaxxonNoFrameskip-v4"
)

# Loop through each environment and run the trainer
for env in "${envs[@]}"; do
    echo "--------------------------------------------------"
    echo "Starting training for: $env"
    echo "--------------------------------------------------"

    python3 ./sb3_agents/trainer.py --emulator ale --env "$env"

    echo "Finished training for: $env"
done