# https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/ppo.yml
# https://github.com/kengz/SLM-Lab/blob/master/slm_lab/spec/benchmark_arc/ppo/ppo_atari_arc.yaml


ale:
  normalize: false
  frame_stack: 4
  policy: 'CnnPolicy'
  n_envs: 16
  n_steps: 128
  gamma: 0.99
  gae_lambda: 0.95
  n_epochs: 4
  batch_size: 256
  n_timesteps: !!float 1e7
  learning_rate: !!float 2.5e-4
  clip_range: 0.1
  vf_coef: 0.5
  ent_coef: 0.01
  normalize_advantage: true
  max_grad_norm: 0.5
  policy_kwargs:
    optimizer_class: 'AdamW'
    optimizer_kwargs:
      eps: !!float 1.0e-5
    ortho_init: true
    activation_fn: 'relu'
  eval_freq: 10000